FROM ubuntu:latest

# Aggiornamento dei repository, installazione di java e maven
RUN apt-get update && apt-get install -y openjdk-17-jdk

# Installare Python e relative librerie
RUN apt-get install -y python3 && apt-get install -y python3-pip 
RUN pip3 install xpress=='9.0.7'

RUN mkdir /Challenge
COPY /target/scheduling-jar-with-dependencies.jar /Challenge
COPY config.xml /Challenge

WORKDIR /Challenge

RUN chmod 775 scheduling-jar-with-dependencies.jar 

EXPOSE 8080
ENTRYPOINT [ "java", "jar", "scheduling-jar-with-dependencies.jar"]