FROM ubuntu:latest

# Aggiornamento dei repository, installazione di java e maven
RUN apt-get update && apt-get install -y openjdk-17-jdk

# Installare Python e relative librerie
RUN apt-get install -y python3 && apt-get install -y python3-pip 
RUN pip3 install statsmodels && pip install pandas

RUN mkdir /Challenge
COPY /target/forecasting-jar-with-dependencies.jar /Challenge
COPY config.xml /Challenge

WORKDIR /Challenge

RUN chmod 775 forecasting-jar-with-dependencies.jar 

EXPOSE 8080
ENTRYPOINT [ "java", "jar", "forecasting-jar-with-dependencies.jar"]