FROM eclipse-temurin:17-jre-focal

RUN mkdir /Challenge
COPY /target/kafka-jar-with-dependencies.jar /Challenge
COPY config.xml /Challenge

WORKDIR /Challenge

RUN chmod 775 kafka-jar-with-dependencies.jar 

EXPOSE 8080
ENTRYPOINT [ "java", "jar", "kafka-jar-with-dependencies.jar"]